build_from:
  aarch64: "python:3.11-alpine"

labels:
  org.opencontainers.image.title: "PWM LED Controller"
  org.opencontainers.image.description: "Hardware PWM control for Raspberry Pi 5"
  org.opencontainers.image.source: "https://github.com/KoToValery/PWM"
  org.opencontainers.image.licenses: "MIT"
